spring:
  cloud:
    aws:
      region:
        static: eu-north-1
      sqs:
        queue-name: s3-events-queue
  output:
    ansi:
      enabled: always

  batch:
    job:
      enabled: false
sqs:
  queue-name: s3-events-queue


logging:
  level:
    org.springframework.integration: DEBUG
    org.springframework.integration.ftp: DEBUG
    org.apache.commons.net.ftp: DEBUG